language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PACKAGE="mirage-stack"
  - PINS="mirage-stack:. mirage-device.2.0.0:git+https://github.com/hannesm/mirage-device.git#easy mirage-protocols.4.0.0:git+https://github.com/hannesm/mirage-protocols.git#easy mirage-flow.2.0.0:git+https://github.com/hannesm/mirage-flow.git#easy mirage-net.3.0.0:git+https://github.com/hannesm/mirage-net.git#easy"
  - REVDEPS=true
  matrix:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
